create table public.johnwick_board_posts (
  id bigint generated by default as identity primary key,
  title text not null,
  content text not null,
  author text not null,
  access_code text not null,
  created_at timestamp with time zone default timezone('Asia/Seoul', now()) not null,
  likes integer default 0,
  dislikes integer default 0
);


create table public.johnwick_board_comments (
  id bigint generated by default as identity primary key,
  post_id bigint references public.johnwick_board_posts(id) on delete cascade,
  content text not null,
  author text not null,
  created_at timestamp with time zone default timezone('Asia/Seoul', now()) not null
);


insert into public.johnwick_board_posts
(title, content, author, access_code, created_at, likes, dislikes)
values
(
  '첫 방문한 Continental의 추억',
  '
  고요한 밤, 컨티넨탈 호텔의 입구는 찬란하게 빛난다.
  <figure class="image">
    <img src="/hotel.png" alt="호텔 입구" />
  </figure>
  ',
  'John Wick',
  'continental42',
  '2025-05-28',
  3,
  0
),
(
  '살아남기 위한 훈련의 기록',
  '
  매일 새벽, 이곳은 전장의 전초기지처럼 변한다. 강철 같은 눈빛과 주먹, 그리고 흐르는 땀이 컨티넨탈의 룰을 지킨다.
  <figure class="image">
    <img src="/trainer.png" alt="트레이닝 센터" />
  </figure>
  ',
  'Winston',
  'continental42',
  '2025-05-28',
  5,
  1
);



insert into public.johnwick_board_comments (post_id, content, author, created_at)
values
(1, '정말 멋진 순간이었겠네요. 컨티넨탈의 입구는 언제 봐도 감탄이 나옵니다.', 'Charon', '2025-06-05 14:00:00'),
(1, '그 장면, 저도 기억나요. 조용한 긴장감이 흐르던 그 밤!', 'Sharon', '2025-06-05 14:10:00'),
(2, '트레이닝 센터는 정말 무시무시하죠. 매번 가슴이 철렁해요.', 'Cassian', '2025-06-05 14:15:00'),
(2, '그곳은 단련의 끝판왕. 존 윅도 거기서 훈련했겠죠?', 'Ares', '2025-06-05 14:20:00');


ALTER TABLE johnwick_board_comments
ADD COLUMN access_code TEXT;